# Lista 2

In [1]:
import numpy as np
from scipy import linalg

In [2]:
def eliminacja_gaussa_z_wyborem(A, b):
  n = len(b)
  x = np.zeros(n)

  # Eliminacja współczynników
  for k in range(n-1):
    # Wybór elementu podstawowego
    max_index = k + np.argmax(np.abs(A[k:, k]))
    if max_index != k:
      A[[k, max_index]] = A[[max_index, k]]
      b[[k, max_index]] = b[[max_index, k]]

    for i in range(k+1, n):
      factor = A[i, k] / A[k, k]
      A[i, k:] -= factor * A[k, k:]
      b[i] -= factor * b[k]

  # Podstawianie wstecz
  x[n-1] = b[n-1] / A[n-1, n-1]
  for i in range(n-2, -1, -1):
    x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

  return x

## zadanie 4

In [35]:
A = np.array([[0,0,2,1,2], [0,1,0,2,-1,],[1,2,0,-2,0],[0,0,0,-1,1],[0,1,-1,1,-1]], dtype=float)
b = np.array([[1], [1], [-4], [-2], [-1]], dtype=float)
b4 = np.array([1, 1, -4, -2, -1], dtype=float)
x4 = np.linalg.solve(A, b4)
x = np.linalg.solve(A, b)
x

array([[ 2.],
       [-2.],
       [ 1.],
       [ 1.],
       [-1.]])

In [36]:
x4 = eliminacja_gaussa_z_wyborem(A,b4)
print(x4)

[ 2. -2.  1.  1. -1.]


## zadanie 5

In [15]:
# Punkty, przez które przechodzi wielomian
punkty = np.array([[0, -1], [2, 2], [3, 3], [1, 4], [6, -2]], dtype=float)

# Macierz współczynników i wektor wyrazów wolnych
A = np.zeros((5, 5))
b = punkty[:, 1]
for i in range(5):
  for j in range(5):
    A[i, j] = punkty[i, 0]**j

# Rozwiązanie układu równań
wspolczynniki = eliminacja_gaussa_z_wyborem(A.copy(), b.copy())

# Wypisanie wielomianu
print("Wielomian:")
print("y =", wspolczynniki[0], "+", wspolczynniki[1], "* x +", wspolczynniki[2], "* x^2 +", wspolczynniki[3], "* x^3 +", wspolczynniki[4], "* x^4")

Wielomian:
y = -1.0 + 13.933333333333337 * x + -12.350000000000001 * x^2 + 3.7666666666666666 * x^3 + -0.35000000000000003 * x^4


In [27]:
def y(x):
  return -1.0 + 13.933333333333337 * x + -12.350000000000001 * x**2 + 3.7666666666666666 * x**3 + -0.35000000000000003 * x**4
print(y(0), y(2), y(3), y(1), y(6))

-1.0 2.000000000000001 3.000000000000007 4.000000000000003 -2.0


In [16]:
A5 = np.array([[x**i for i in range(5)] for x, _ in punkty], dtype=float)
b5 = punkty[:, 1]

wspolczynniki2 = eliminacja_gaussa_z_wyborem(A5, b5)
print("Zadanie 5 - Współczynniki wielomianu:", wspolczynniki2)

Zadanie 5 - Współczynniki wielomianu: [ -1.          13.93333333 -12.35         3.76666667  -0.35      ]


## zadanie 6

In [26]:
A = np.array([[3.50, 2.77, -0.76, 1.80],
             [-1.80, 2.68, 3.44, -0.09],
             [0.27, 5.07, 6.90, 1.61],
             [1.71, 5.45, 2.68, 1.71]], dtype = float)
b = np.array([7.31, 4.23, 13.85, 11.55], dtype = float)
x6 = eliminacja_gaussa_z_wyborem(A, b)
det_A6 = np.linalg.det(A)
Ax6 = np.dot(A, x6)

print('Rozwiązanie x:', x6)
print("Det(A):", det_A6)
print("Dokładność Ax ≈ b:", Ax6, "≈", b)
print(f"różnica: {Ax6 - b}")

Rozwiązanie x: [1. 1. 1. 1.]
Det(A): 0.22579734000000876
Dokładność Ax ≈ b: [ 7.31000000e+00  1.32860857e+01 -3.24001100e+00 -4.69032638e-03] ≈ [ 7.31000000e+00  1.32860857e+01 -3.24001100e+00 -4.69032638e-03]
różnica: [8.8817842e-16 0.0000000e+00 0.0000000e+00 0.0000000e+00]


## zadanie 7

In [37]:
A = np.array([[10, -2, -1, 2, 3, 1, -4, 7],
              [5, 11, 3, 10, -3, 3, 3, -4],
              [7, 12, 1, 5, 3, -12, 2, 3],
              [8, 7, -2, 1, 3, 2, 2, 4],
              [2, -15, -1, 1, 4, -1, 8, 3],
              [4, 2, 9, 1, 12, -1, 4, 1],
              [-1, 4, -7, -1, 1, 1, -1, -3],
              [-1, 3, 4, 1, 3, -4, 7, 6]], dtype = float)
x = np.array([[0], [12], [-5], [3], [-25], [-26], [9], [-7]], dtype = float)
x7 = np.array([0, 12, -5, 3, -25, -26, 9, -7], dtype = float)
eliminacja_gaussa_z_wyborem(A, x7)

array([-1.,  1., -1.,  1., -1.,  1., -1.,  1.])

## zadanie 8

In [66]:
A = np.array([[2, -1, 0, 0, 0, 0],
              [-1, 2, -1, 0, 0, 0],
              [0, -1, 2, -1, 0, 0],
              [0, 0, -1, 2, -1, 0],
              [0, 0, 0, -1, 2, -1],
              [0, 0, 0, 0, -1, 5]], dtype = float)
I = np.eye(A.shape[0])
print(I)
A_inv = np.column_stack([eliminacja_gaussa_z_wyborem(A.copy(), I[:, i].copy()) for i in range(len(I[0]))])
A_inv

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


array([[0.84, 0.68, 0.52, 0.36, 0.2 , 0.04],
       [0.68, 1.36, 1.04, 0.72, 0.4 , 0.08],
       [0.52, 1.04, 1.56, 1.08, 0.6 , 0.12],
       [0.36, 0.72, 1.08, 1.44, 0.8 , 0.16],
       [0.2 , 0.4 , 0.6 , 0.8 , 1.  , 0.2 ],
       [0.04, 0.08, 0.12, 0.16, 0.2 , 0.24]])

In [67]:
A*A_inv, np.round(A @ A_inv, decimals=2)

(array([[ 1.68, -0.68,  0.  ,  0.  ,  0.  ,  0.  ],
        [-0.68,  2.72, -1.04,  0.  ,  0.  ,  0.  ],
        [ 0.  , -1.04,  3.12, -1.08,  0.  ,  0.  ],
        [ 0.  ,  0.  , -1.08,  2.88, -0.8 ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.8 ,  2.  , -0.2 ],
        [ 0.  ,  0.  ,  0.  ,  0.  , -0.2 ,  1.2 ]]),
 array([[ 1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -0.,  0.,  0.,  0.],
        [-0., -0.,  1.,  0.,  0., -0.],
        [ 0.,  0., -0.,  1.,  0.,  0.],
        [-0., -0.,  0.,  0.,  1.,  0.],
        [-0., -0.,  0., -0., -0.,  1.]]))

In [56]:
is_tridiagonal = np.allclose(A_inv, np.triu(np.tril(A_inv, 1), -1))
print("Czy macierz A^-1 jest trójdiagonalna?", is_tridiagonal)

Czy macierz A^-1 jest trójdiagonalna? False


## zadanie 9

In [71]:
A = np.array([
    [1, 3, -9, 6, 4],
    [2, -1, 6, 7, 1],
    [3, 2, -3, 15, 5],
    [8, -1, 1, 4, 2],
    [11, 1, -2, 18, 7]
], dtype=float)
I = np.eye(A.shape[0])
A_inv = np.column_stack([eliminacja_gaussa_z_wyborem(A.copy(), I[:, i]) for i in range(len(I[1]))])

In [72]:
A_inv

array([[-7.42166231e+14, -7.42166231e+14, -7.42166231e+14,
        -1.48433246e+15,  1.48433246e+15],
       [-3.52528960e+15, -3.52528960e+15, -3.52528960e+15,
        -7.05057919e+15,  7.05057919e+15],
       [-5.90359502e+14, -5.90359502e+14, -5.90359502e+14,
        -1.18071900e+15,  1.18071900e+15],
       [-0.00000000e+00, -0.00000000e+00,  1.00000000e+00,
         1.00000000e+00, -1.00000000e+00],
       [ 1.50119988e+15,  1.50119988e+15,  1.50119988e+15,
         3.00239975e+15, -3.00239975e+15]])

In [73]:
A*A_inv, np.round(A @ A_inv, decimals=2)

(array([[-7.42166231e+14, -2.22649869e+15,  6.67949608e+15,
         -8.90599477e+15,  5.93732985e+15],
        [-7.05057919e+15,  3.52528960e+15, -2.11517376e+16,
         -4.93540543e+16,  7.05057919e+15],
        [-1.77107851e+15, -1.18071900e+15,  1.77107851e+15,
         -1.77107851e+16,  5.90359502e+15],
        [-0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          4.00000000e+00, -2.00000000e+00],
        [ 1.65131986e+16,  1.50119988e+15, -3.00239975e+15,
          5.40431955e+16, -2.10167983e+16]]),
 array([[ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ],
        [ 0.  ,  0.25, -0.25,  0.  ,  0.  ],
        [-1.  ,  0.25,  2.25,  0.  ,  0.  ],
        [-1.  , -0.5 ,  0.  ,  1.  , -1.  ],
        [-1.  ,  0.75,  0.75,  0.  ,  0.  ]]))

In [75]:
np.linalg.det(A)

1.9761969838327938e-14

Wyznacznik jest bliski zera → macierz jest źle uwarunkowana, dlatego występują znaczne błędy numeryczne w rozwiązaniu.